//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbPruebaNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancelacione
    {
        public string OC { get; set; }
        public string PRECIO_DESPACHO { get; set; }
        public string MONTO_TOTAL_LINEA { get; set; }
        public string SKU_LINEA { get; set; }
        public string F12 { get; set; }
        public string TIPO_ABASTECIMIENTO { get; set; }
        public string DUP_OC { get; set; }
        public string DUP_F12 { get; set; }
        public string ESTADO_LINEA { get; set; }
        public string ESTADO_ORDEN_OMS { get; set; }
        public string ESTADO_CD { get; set; }
    }
}
