//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbPruebaNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dato
    {
        public string OC { get; set; }
        public string F12 { get; set; }
        public string SKU { get; set; }
        public string CC { get; set; }
        public string ESTADO { get; set; }
    }
}
